---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: true
  require_ansible_omnibus: false
  ansible_verbose: true
  ansible_verbosity: <%= ENV['ANSIBLE_VERBOSITY'] || 1 %>
  ansible_diff: true
  roles_path: ../../roles
  require_chef_for_busser: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    transport:
      max_ssh_sessions: 6

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
      attributes:
        service_type: sysv
