---
- name: Configure MySQL DebConf Questions
  debconf:
    name: "{{ ez_mysql.package }}"
    question: "{{ ez_mysql.package }}/{{ item }}"
    value: "{{ ez_mysql.database.root_password }}"
    vtype: password
  with_items:
    - root_password
    - root_password_again

- name: Install MySQL package
  apt:
    name: "{{ ez_mysql.package }}"
    state: present
    update_cache: yes
