---
- name: Start/Enable MySQL Service (Docker)
  service:
    name: "{{ ez_mysql.service }}"
    state: started
    enabled: yes
    use: service
  when: ohai_virtualization.system == "docker"
  
- name: Start/Enable MySQL Service (Docker)
  service:
    name: "{{ ez_mysql.service }}"
    state: started
    enabled: yes
  when: ohai_virtualization.system != "docker"
