---
driver:
  name: vagrant
  provider: hyperv

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: true
  require_ansible_omnibus: false
  ansible_verbose: true
  ansible_verbosity: 1
  ansible_diff: true
  ansible_cfg_path: ../../../inspec/ez_apache/test/integration/default/ansible.cfg
  roles_path: ../../roles
  require_chef_for_busser: true
  playbook: ../../../inspec/ez_apache/test/integration/default/default.yml

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    verifier:
      inspec_tests:
        - ../../../inspec/ez_apache/test/integration/default
    provisioner:
      extra_vars:
        ez_mysql:
          database:
            root_password: 'iloverandompasswordsbutthiswilldo'
