galaxy_info:
  author: Joaquin Menchaca
  description: EZ MySQL is a simple cookbook that installs MySQL server with databases required to run WordPress.
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - 16.04
